galaxy_info:
  author: Red Hat
  description: OCP Console Embed Role
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Openshift
      versions:
        - all
  galaxy_tags:
    - openshift
    - console
    - embed
    - iframe

dependencies: []
