---
become_override: false
silent: false

# Optional, role-scoped override for the OpenShift API URL used by this role.
# If set, this value will be preferred over any globally-defined `openshift_api_url`.
ocp4_workload_showroom_ocp_integration_openshift_api_url: ""

# Optional, role-scoped override for the OpenShift API token used by this role.
# If unset, this role will fall back to (in order): `openshift_cluster_admin_token`,
# then `openshift_api_token`, and finally any existing `openshift_api_key`.
ocp4_workload_showroom_ocp_integration_openshift_api_token: ""
