---
- name: Clone and Inject Showroom repo and vars
  block:

    - name: Clone showroom primary repo - lab content in adoc
      ansible.builtin.git:
        repo: "{{ showroom_git_repo }}"
        dest: "{{ showroom_user_content_dir }}"
        force: true
        version: "{{ showroom_git_ref | default(showroom_git_tag) | default('main') }}"
      become_user: "{{ showroom_user }}"

    - name: Setup and inject userdata into showroom repo
      when: showroom_var_inject | default(true) | bool
      block:

        - name: Set f_user_data
          ansible.builtin.set_fact:
            f_user_data: "{{ lookup('agnosticd.core.agnosticd_user_data', '*') | from_yaml }}"

        - name: Fetch antora.yml from the showroom content dir
          ansible.builtin.slurp:
            src: "{{ showroom_user_content_dir }}/content/antora.yml"
          register: r_slurp_antora_yml

        - name: Write merged_vars to a file
          ansible.builtin.copy:
            content: >-
              {{ __src | combine(__attribute_user_data, recursive=true) | to_nice_yaml(indent=2) }}
            dest: "{{ showroom_user_content_dir }}/content/antora.yml"
            owner: "{{ showroom_user }}"
            group: "{{ showroom_user_group }}"
          vars:
            __attribute_user_data:
              asciidoc:
                attributes: "{{ f_user_data }}"
            __src: "{{ r_slurp_antora_yml.content | b64decode | from_yaml }}"
